services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    networks:
      - hbase
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - namenode:/hadoop/dfs/name
      - ./NASA_access_log_Aug95:/tmp/NASA_access_log_Aug95
      - ./NASA_access_log_Jul95:/tmp/NASA_access_log_Jul95
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    networks:
      - hbase
    volumes:
      - datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    environment:
      SERVICE_PRECONDITION: "namenode:9870"

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    networks:
      - hbase
    ports:
      - "8088:8088"
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075"
    env_file:
      - ./hadoop.env

  nodemanager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    networks:
      - hbase
    ports:
      - "8042:8042"
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
    env_file:
      - ./hadoop.env

  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    networks:
      - hbase
    ports:
      - "8188:8188"
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
    env_file:
      - ./hadoop.env

  spark:
    image: apache/spark:3.5.1
    networks:
      - hbase
    ports:
      - "4040:4040"
    volumes:
      - ./job.py:/app/job.py
    environment:
      - PYSPARK_PYTHON=python3
    command: >
      bash -c "sleep 30 && /opt/spark/bin/spark-submit --master local[*] /app/job.py"

volumes:
  datanode:
  namenode:
  hadoop_historyserver:

networks:
  hbase:
    name: hbase